### PR TITLE
[WIP] Full dual-stack IPv4/IPv6 support including link scope IDs

### PR DESCRIPTION
**Pull request by alexander255**
See #12

### CODE REVIEW

**Comment by agoode** [comment]
Can you rebase on top of #14 ?

**Comment by mgorny** [comment]
I've just tested this pull request and it doesn't seem to work with scope-local addresses for me.

```
$ ping6 pomiocik.local
connect: Invalid argument
$ strace ping6 pomiocik.local
[...]
socket(AF_INET6, SOCK_DGRAM, IPPROTO_IP) = 3
connect(3, {sa_family=AF_INET6, sin6_port=htons(1025), inet_pton(AF_INET6, "fe80::da50:e6ff:fea4:bd95", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)
```

**Comment by mgorny** [comment]
FYI, I'm going to look into rebasing those patches and fixing them as necessary.

**Comment by agoode** [comment]
Obsoleted by #20.

**Pull request closed without merging**
