### PR TITLE
Rebased & fixed Alexander's IPv6 patches

### PR DESCRIPTION
**Pull request by mgorny**
This is #13 rebased against current master with a few fixes. I've fixed the interim commit to return protocol correctly for nss*_3 and less APIs, and I've also fixed the avahi reverse resolution test to work after enabling IPv6 branch.

### CODE REVIEW

**Comment by mgorny** [comment]
@agoode, @amynka: good news, is that it seems that I didn't break anything. Bad news, it still doesn't work with scopes for me. I've spent a few hours debugging this already, and I see no apparent reason. I've even went as far as to modify nss-test to use getaddrinfo()+getnameinfo() — and it apparently gets the scope id just fine when run in build tree. However, after installing it it no longer works as expected…

**Comment by mgorny** [comment]
Ok, I suspect something now. It seems that `ping` and other system programs call `_nss_mdns_gethostbyname3_r()` instead of `...4_r()` — which in nss-mdns doesn't support scopes. Curious enough, the Gentoo patch somehow managed to get them in.

AFAICS, the Gentoo patch simply added the scope after the IPv6 address, therefore changing its length from 16 to 20 bytes. I honestly doubt that's correct. I suspect the older version of glibc simply passed the wrong size through, and the overflow ended up filling `sin6_scope` field following `sin6_addr`. But that's only an unconfirmed suspicion. It could also explain why it suddenly started segfaulting.

**Comment by mgorny** [comment]
Please disregard my doubts. It turns out to being a [glibc bug wrt reso with AF_INET6](https://sourceware.org/bugzilla/show_bug.cgi?id=16826). We can't really do anything about it. For resolutions with AF_UNSPEC, the patch works just fine.

**Comment by agoode** [comment]
Thanks! This looks good at first glance, though I want to review it a bit more.

Could you please redo this a bit and introduce new commits for your fixes? I would like to keep the authorship clear.

**Comment by mgorny** [comment]
I'd rather not attempt to do that since the thing was really painful to rebase. More of the work involved fighting failed merges than any direct changes on the code. The latter were minor enough not to be copyrightable, and to be honest -- I'm not even sure how much I've actually fixed of the original commits, and how much of my failure to merge it correctly ;-).

**Comment by mgorny** [comment]
Here's the diff between the patches. Unless otherwise noted, they're purely changes related to rebasing on current master.

```diff
-From 184d01b2a73cce44b2b4734678fd65200dd36db7 Mon Sep 17 00:00:00 2001
+From 5fa5f9686edab0562f4e4e4b2b635d162245a2d6 Mon Sep 17 00:00:00 2001
 From: Alexander Schlarb <alexander@xmine128.tk>
 Date: Sat, 12 Mar 2016 13:16:56 +0100
-Subject: [PATCH 3/4] Implement _nss_mdns_gethostbyname3_r and
+Subject: [PATCH 2/3] Implement _nss_mdns_gethostbyname3_r and
  _nss_mdns_gethostbyname4_r
 
 ---
- src/avahi-test.c |  16 ++--
+ src/avahi-test.c |  18 ++--
  src/avahi.c      |   8 +-
  src/avahi.h      |  18 +++-
  src/map-file     |  18 ++++
- src/nss.c        | 273 ++++++++++++++++++++++++++++++++++++-------------------
- 5 files changed, 230 insertions(+), 103 deletions(-)
+ src/nss.c        | 293 ++++++++++++++++++++++++++++++++++++-------------------
+ 5 files changed, 242 insertions(+), 113 deletions(-)
 
 diff --git a/src/avahi-test.c b/src/avahi-test.c
-index e57d8b2..cd3228f 100644
+index e57d8b2..066f871 100644
 --- a/src/avahi-test.c
 +++ b/src/avahi-test.c
-@@ -26,21 +26,21 @@
+@@ -26,24 +26,24 @@
  #include "avahi.h"
  
  int main(int argc, char *argv[]) {
@@ -311,16 +63,20 @@ index e57d8b2..cd3228f 100644
 -/*         printf("AF_INET6: %s\n", inet_ntop(AF_INET6, data, t, sizeof(t))); */
 -/*     else */
 -/*         printf("AF_INET6: failed (%i).\n", r); */
-+    if ((r = avahi_resolve_name(AF_INET6, argc >= 2 ? argv[1] : "cocaine.local", &result)) == 0)
-+        printf("AF_INET6: %s\n", inet_ntop(AF_INET6, &(result.address.ipv6), t, sizeof(t)));
-+    else
-+        printf("AF_INET6: failed (%i).\n", r);
- 
+-
 -    if ((r = avahi_resolve_address(AF_INET, data, t, sizeof(t))) == 0)
-+    if ((r = avahi_resolve_address(AF_INET, t, &(result.address.ipv4), sizeof(t))) == 0)
++    if ((r = avahi_resolve_address(AF_INET, &(result.address.ipv4), t, sizeof(t))) == 0)
          printf("REVERSE: %s\n", t);
      else
          printf("REVERSE: failed (%i).\n", r);
```

Here I fixed reversed parameter order (probably accidentally), too small change to be copyrightable.

```diff
+ 
++    if ((r = avahi_resolve_name(AF_INET6, argc >= 2 ? argv[1] : "cocaine.local", &result)) == 0)
++        printf("AF_INET6: %s\n", inet_ntop(AF_INET6, &(result.address.ipv6), t, sizeof(t)));
++    else
++        printf("AF_INET6: failed (%i).\n", r);
++
```

I've moved this test below reverse test.

```diff
+     return 0;
+ }
 diff --git a/src/avahi.c b/src/avahi.c
 index dbe61b3..94e3857 100644
 --- a/src/avahi.c
@@ -437,11 +193,11 @@ index 0bd067f..fbc16b9 100644
  *;
  };
 diff --git a/src/nss.c b/src/nss.c
-index 4f6e451..c3f6b91 100644
+index 2545da8..d737158 100644
 --- a/src/nss.c
 +++ b/src/nss.c
-@@ -36,28 +36,40 @@
- #include "avahi.h"
+@@ -37,28 +37,40 @@
+ #include "util.h"
  
  #if defined(NSS_IPV4_ONLY) && ! defined(MDNS_MINIMAL)
 +#define _nss_mdns_gethostbyname4_r _nss_mdns4_gethostbyname4_r
@@ -481,7 +237,7 @@ index 4f6e451..c3f6b91 100644
  enum nss_status _nss_mdns_gethostbyname2_r(const char*, int, struct hostent*, char*, size_t, int*, int*);
  enum nss_status _nss_mdns_gethostbyname_r (const char*, struct hostent*, char*, size_t, int*, int*);
  enum nss_status _nss_mdns_gethostbyaddr_r (const void*, int, int, struct hostent*, char *, size_t, int *, int *);
-@@ -70,49 +82,26 @@ enum nss_status _nss_mdns_gethostbyaddr_r (const void*, int, int, struct hostent
+@@ -71,49 +83,26 @@ enum nss_status _nss_mdns_gethostbyaddr_r (const void*, int, int, struct hostent
      idx += (sizeof(void*) - idx % sizeof(void*)); /* Align on word boundary */ \
  } while(0)
  
@@ -538,8 +294,8 @@ index 4f6e451..c3f6b91 100644
  
  static void name_callback(const char*name, void *userdata) {
      struct userdata *u = userdata;
-@@ -183,22 +172,18 @@ static int verify_name_allowed(const char *name) {
-     return ends_with(name, ".local") || ends_with(name, ".local."); 
+@@ -126,33 +115,24 @@ static void name_callback(const char*name, void *userdata) {
+     u->data_len += strlen(name)+1;
  }
  
 -enum nss_status _nss_mdns_gethostbyname2_r(
@@ -550,8 +306,6 @@ index 4f6e451..c3f6b91 100644
 -    size_t buflen,
 -    int *errnop,
 -    int *h_errnop) {
--
--    struct userdata u;
 +static enum nss_status gethostbyname_impl(
 +        const char *name, int af,
 +        struct userdata *u,
@@ -559,7 +313,10 @@ index 4f6e451..c3f6b91 100644
 +        int *errnop,
 +        int *h_errnop
 +    ) {
-+    
+ 
+-    FILE *mdns_allow_file = NULL;
+-    int name_allowed;
+-    struct userdata u;
      enum nss_status status = NSS_STATUS_UNAVAIL;
 -    int i;
 -    size_t address_length, l, idx, astart;
@@ -568,11 +325,23 @@ index 4f6e451..c3f6b91 100644
 -    void * data[32];
 +
 +    int avahi_works = 1;
++    int name_allowed;
++    FILE *mdns_allow_file = NULL;
 +    query_address_result_t address_result;
  
  /*     DEBUG_TRAP; */
  
-@@ -220,51 +205,141 @@ enum nss_status _nss_mdns_gethostbyname2_r(
+-    if (af == AF_UNSPEC)
+-#ifdef NSS_IPV6_ONLY
+-        af = AF_INET6;
+-#else
+-        af = AF_INET;
+-#endif
++    assert(af != AF_UNSPEC);
```

I've moved this conditional out of the sub-function as otherwise `af` was left as AF_UNSPEC in this code, and returned to nss as such with a valid address. It's only a moved code, and basically also what was already done in the commit following it. See below.

```diff
+ 
+ #ifdef NSS_IPV4_ONLY
+     if (af != AF_INET) 
+@@ -165,35 +145,13 @@ enum nss_status _nss_mdns_gethostbyname2_r(
          *errnop = EINVAL;
          *h_errnop = NO_RECOVERY;
  
@@ -591,28 +360,32 @@ index 4f6e451..c3f6b91 100644
 -        
 -        goto finish;
 -    }
-+    *address_length = (af == AF_INET ? sizeof(ipv4_address_t) : sizeof(ipv6_address_t));
-     
+-    
 -    u.count = 0;
 -    u.data_len = 0;
-+    u->count = 0;
-+    u->data_len = 0;
++    *address_length = (af == AF_INET ? sizeof(ipv4_address_t) : sizeof(ipv6_address_t));
  
 -#ifdef NSS_IPV6_ONLY
 -    ipv4_func = NULL;
 -#else
 -    ipv4_func = af == AF_INET ? ipv4_callback : NULL;
 -#endif    
- 
+-
 -#ifdef NSS_IPV4_ONLY
 -    ipv6_func = NULL;
 -#else
 -    ipv6_func = af == AF_INET6 ? ipv6_callback : NULL;
 -#endif
-+    if (avahi_works && verify_name_allowed(name)) {
-+        int r;
++    u->count = 0;
++    u->data_len = 0;
  
--    if (verify_name_allowed(name)) {
+ #ifndef MDNS_MINIMAL
+     mdns_allow_file = fopen(MDNS_ALLOW_FILE, "r");
+@@ -203,21 +161,140 @@ enum nss_status _nss_mdns_gethostbyname2_r(
+     if (mdns_allow_file)
+         fclose(mdns_allow_file);
+ #endif
+-    if (name_allowed) {
 -        int r = avahi_resolve_name(af, name, data);
 -        if (r == 0) {
 -            if (af == AF_INET && ipv4_func)
@@ -620,6 +393,9 @@ index 4f6e451..c3f6b91 100644
 -            if (af == AF_INET6 && ipv6_func)
 -                ipv6_func((ipv6_address_t*)data, &u);
 -        } else if (r > 0)
++    if (avahi_works && name_allowed) {
++        int r;
++
 +        if ((r = avahi_resolve_name(af, name, &address_result)) < 0)
 +            avahi_works = 0;
 +        else if (r == 0) {
@@ -646,14 +422,14 @@ index 4f6e451..c3f6b91 100644
 +        int *errnop, int *h_errnop,
 +        int32_t *ttlp
 +    ) {
-+    
++
 +    int i;
 +    size_t address_length, idx;
 +    char *buffer_name;
 +    struct gaih_addrtuple *tuple_prev;
 +
 +    int af = AF_INET6; //TODO: Support AF_UNSPEC dual-stack IP
-+    
++
 +    struct userdata u;
 +
 +    // Since populating the buffer works differently in `gethostbyname[23]?` than in
@@ -662,7 +438,7 @@ index 4f6e451..c3f6b91 100644
 +    if(status != NSS_STATUS_SUCCESS) {
 +        return status;
 +    }
-+    
++
 +    /* Check if there's enough space for the addresses */
 +    // strlen(name)+1                        - Host name string
 +    // sizeof(struct gaih_addrtuple)*u.count - All address result structures
@@ -672,46 +448,46 @@ index 4f6e451..c3f6b91 100644
 +        *h_errnop = NO_RECOVERY;
 +        return NSS_STATUS_TRYAGAIN;
 +    }
-+    
++
 +    idx = 0;
-+    
++
 +    // Copy name to buffer (referenced in every result address tuple)
 +    buffer_name = buffer + idx;
-+    strcpy(buffer_name, name); 
++    strcpy(buffer_name, name);
 +    idx += strlen(buffer_name) + 1;
 +    ALIGN(idx);
 +
 +    tuple_prev = NULL;
 +    for (i = 0; i < u.count; i++) {
 +        struct gaih_addrtuple *tuple = (struct gaih_addrtuple*) (buffer+idx);
-+        
++
 +        // Will be overwritten by next address assignment (if there is one)
 +        tuple->next = NULL;
-+        
++
 +        // Assign the (always same) name
 +        tuple->name = buffer_name;
-+        
++
 +        //TODO: Support IPv4/IPv6 dual-stack
 +        tuple->family = af;
-+        
++
 +        // Copy address
 +        memcpy(&(tuple->addr), &(u.data.result[i].address), address_length);
 +        if(address_length < 16) {
 +            memset((&(tuple->addr) + address_length - 16), 0, (16 - address_length));
 +        }
-+        
++
 +        // Assign interface scope id
 +        tuple->scopeid = u.data.result[i].scopeid;
-+        
++
 +        // Link in previous address tuple
 +        if(tuple_prev == NULL) {
 +            *pat = tuple;
 +        } else {
 +            tuple_prev->next = tuple;
 +        }
-+        
++
 +        ALIGN(idx);
-+        
++
 +        tuple_prev = tuple;
 +    }
 +
@@ -732,23 +508,31 @@ index 4f6e451..c3f6b91 100644
 +    size_t address_length, idx, astart;
 +
 +    struct userdata u;
-+    
-+    enum nss_status status = gethostbyname_impl(name, af, &u, &address_length, errnop, h_errnop);
++    enum nss_status status;
++
++    if (af == AF_UNSPEC)
++#ifdef NSS_IPV6_ONLY
++        af = AF_INET6;
++#else
++        af = AF_INET;
++#endif
```

Moved it here.

```diff
++
++    status = gethostbyname_impl(name, af, &u, &address_length, errnop, h_errnop);
 +    if(status != NSS_STATUS_SUCCESS) {
 +        return status;
 +    }
-+    
++
 +    if (buflen <
 +        sizeof(char*)+    // alias names
 +        strlen(name)+1)  {   // official name
-+        
++
 +        *errnop = ERANGE;
 +        *h_errnop = NO_RECOVERY;
 +        return NSS_STATUS_TRYAGAIN;
      }
      
      /* Alias names */
-@@ -286,29 +361,45 @@ enum nss_status _nss_mdns_gethostbyname2_r(
+@@ -239,29 +316,45 @@ enum nss_status _nss_mdns_gethostbyname2_r(
      if (buflen < idx+u.data_len+sizeof(char*)*(u.count+1)+sizeof(void*)) {
          *errnop = ERANGE;
          *h_errnop = NO_RECOVERY;
@@ -766,7 +550,7 @@ index 4f6e451..c3f6b91 100644
 +        memcpy(buffer+idx, &u.data.result[i].address, address_length);
 +        idx += address_length;
 +    }
-+    
++
      /* realign, whilst the address is a multiple of 32bits, we
       * frequently lose alignment for 64bit systems */
      ALIGN(idx);
@@ -807,16 +591,16 @@ index 4f6e451..c3f6b91 100644
  
  enum nss_status _nss_mdns_gethostbyname_r (
 
-From 14800c8979b3b3fdff6cf6d02743716f77f95f27 Mon Sep 17 00:00:00 2001
+From 4d873b291c9593ef61b2ca1a8565afb1534f8a32 Mon Sep 17 00:00:00 2001
 From: Alexander Schlarb <alexander@xmine128.tk>
 Date: Sat, 12 Mar 2016 17:08:09 +0100
-Subject: [PATCH 4/4] Implement full dual-stack IPv4/IPv6 support
+Subject: [PATCH 3/3] Implement full dual-stack IPv4/IPv6 support
 
 ---
  src/avahi.c |  2 ++
  src/avahi.h |  1 +
- src/nss.c   | 92 ++++++++++++++++++++++++++++++++++++++++++++-----------------
- 3 files changed, 69 insertions(+), 26 deletions(-)
+ src/nss.c   | 89 +++++++++++++++++++++++++++++++++++++++++++++----------------
+ 3 files changed, 69 insertions(+), 23 deletions(-)
 
 diff --git a/src/avahi.c b/src/avahi.c
 index 94e3857..3b37022 100644
@@ -844,18 +628,18 @@ index 6e16dd2..fd8418b 100644
          ipv4_address_t ipv4;
          ipv6_address_t ipv6;
 diff --git a/src/nss.c b/src/nss.c
-index c3f6b91..1933b42 100644
+index d737158..75bdee2 100644
 --- a/src/nss.c
 +++ b/src/nss.c
-@@ -172,10 +172,39 @@ static int verify_name_allowed(const char *name) {
-     return ends_with(name, ".local") || ends_with(name, ".local."); 
+@@ -115,10 +115,39 @@ static void name_callback(const char*name, void *userdata) {
+     u->data_len += strlen(name)+1;
  }
  
 +static int do_avahi_resolve_name(int af, const char* name, void* userdata, int* avahi_works) {
 +    query_address_result_t address_result;
 +    int r;
 +    int found = 0;
-+    
++
 +    if (af == AF_INET || af == AF_UNSPEC) {
 +        if ((r = avahi_resolve_name(AF_INET, name, &address_result)) < 0) {
 +            /* Lookup failed */
@@ -866,7 +650,7 @@ index c3f6b91..1933b42 100644
 +            found = 1;
 +        }
 +    }
-+    
++
 +    if (af == AF_INET6 || af == AF_UNSPEC) {
 +        if ((r = avahi_resolve_name(AF_INET6, name, &address_result)) < 0) {
 +            /* Lookup failed */
@@ -877,7 +661,7 @@ index c3f6b91..1933b42 100644
 +            found = 1;
 +        }
 +    }
-+    
++
 +    return found;
 +}
 +
@@ -888,23 +672,16 @@ index c3f6b91..1933b42 100644
          int *errnop,
          int *h_errnop
      ) {
-@@ -183,23 +212,27 @@ static enum nss_status gethostbyname_impl(
-     enum nss_status status = NSS_STATUS_UNAVAIL;
- 
-     int avahi_works = 1;
--    query_address_result_t address_result;
+@@ -132,14 +161,24 @@ static enum nss_status gethostbyname_impl(
  
  /*     DEBUG_TRAP; */
  
--    if (af == AF_UNSPEC)
--#ifdef NSS_IPV6_ONLY
--        af = AF_INET6;
--#else
+-    assert(af != AF_UNSPEC);
 +#ifdef NSS_IPV4_ONLY
 +    if (af == AF_UNSPEC) {
-         af = AF_INET;
++        af = AF_INET;
 +    }
- #endif
++#endif
  
 +#ifdef NSS_IPV6_ONLY
 +    if (af == AF_UNSPEC) {
@@ -922,34 +699,37 @@ index c3f6b91..1933b42 100644
  #endif        
      {    
          *errnop = EINVAL;
-@@ -207,22 +240,15 @@ static enum nss_status gethostbyname_impl(
- 
+@@ -148,8 +187,6 @@ static enum nss_status gethostbyname_impl(
          return status;
      }
--
+ 
 -    *address_length = (af == AF_INET ? sizeof(ipv4_address_t) : sizeof(ipv6_address_t));
-     
+-
      u->count = 0;
      u->data_len = 0;
  
- 
-     if (avahi_works && verify_name_allowed(name)) {
+@@ -161,15 +198,11 @@ static enum nss_status gethostbyname_impl(
+     if (mdns_allow_file)
+         fclose(mdns_allow_file);
+ #endif
+-    if (avahi_works && name_allowed) {
 -        int r;
--
+ 
 -        if ((r = avahi_resolve_name(af, name, &address_result)) < 0)
 -            avahi_works = 0;
 -        else if (r == 0) {
 -            address_callback(&address_result, u);
 -        } else
++    if (avahi_works && name_allowed) {
 +        if(!do_avahi_resolve_name(af, name, u, &avahi_works)) {
              status = NSS_STATUS_NOTFOUND;
 +        }
      }
  
      if (u->count == 0) {
-@@ -243,17 +269,15 @@ enum nss_status _nss_mdns_gethostbyname4_r(
+@@ -190,17 +223,14 @@ enum nss_status _nss_mdns_gethostbyname4_r(
      ) {
-     
+ 
      int i;
 -    size_t address_length, idx;
 +    size_t idx;
@@ -957,7 +737,7 @@ index c3f6b91..1933b42 100644
      struct gaih_addrtuple *tuple_prev;
 -
 -    int af = AF_INET6; //TODO: Support AF_UNSPEC dual-stack IP
-     
+-
      struct userdata u;
  
      // Since populating the buffer works differently in `gethostbyname[23]?` than in
@@ -967,26 +747,26 @@ index c3f6b91..1933b42 100644
      if(status != NSS_STATUS_SUCCESS) {
          return status;
      }
-@@ -280,19 +304,26 @@ enum nss_status _nss_mdns_gethostbyname4_r(
+@@ -227,19 +257,26 @@ enum nss_status _nss_mdns_gethostbyname4_r(
      for (i = 0; i < u.count; i++) {
          struct gaih_addrtuple *tuple = (struct gaih_addrtuple*) (buffer+idx);
-         
+ 
 +        size_t address_length = sizeof(ipv4_address_t);
 +        if(u.data.result[i].af == AF_INET6) {
 +            address_length = sizeof(ipv6_address_t);
 +        }
-+        
++
          // Will be overwritten by next address assignment (if there is one)
          tuple->next = NULL;
-         
+ 
          // Assign the (always same) name
          tuple->name = buffer_name;
-         
+ 
 -        //TODO: Support IPv4/IPv6 dual-stack
 -        tuple->family = af;
 +        // Assign actual address family of address
 +        tuple->family = u.data.result[i].af;
-         
+ 
          // Copy address
          memcpy(&(tuple->addr), &(u.data.result[i].address), address_length);
 -        if(address_length < 16) {
@@ -996,34 +776,37 @@ index c3f6b91..1933b42 100644
 +                (sizeof(ipv6_address_t) - address_length)
 +            );
          }
-         
+ 
          // Assign interface scope id
-@@ -305,6 +336,7 @@ enum nss_status _nss_mdns_gethostbyname4_r(
+@@ -252,6 +289,7 @@ enum nss_status _nss_mdns_gethostbyname4_r(
              tuple_prev->next = tuple;
          }
-         
+ 
 +        idx += sizeof(*tuple);
          ALIGN(idx);
-         
-         tuple_prev = tuple;
-@@ -327,8 +359,14 @@ enum nss_status _nss_mdns_gethostbyname3_r(
-     size_t address_length, idx, astart;
  
+         tuple_prev = tuple;
+@@ -276,14 +314,17 @@ enum nss_status _nss_mdns_gethostbyname3_r(
      struct userdata u;
--    
--    enum nss_status status = gethostbyname_impl(name, af, &u, &address_length, errnop, h_errnop);
-+
+     enum nss_status status;
+ 
+-    if (af == AF_UNSPEC)
 +    // The interfaces for gethostbyname3_r and below do not actually support returning results
 +    // for more than one address family
 +    if(af == AF_UNSPEC) {
-+        af = AF_INET;
+ #ifdef NSS_IPV6_ONLY
+         af = AF_INET6;
+ #else
+         af = AF_INET;
+ #endif
 +    }
-+
-+    enum nss_status status = gethostbyname_impl(name, af, &u, errnop, h_errnop);
+ 
+-    status = gethostbyname_impl(name, af, &u, &address_length, errnop, h_errnop);
++    status = gethostbyname_impl(name, af, &u, errnop, h_errnop);
      if(status != NSS_STATUS_SUCCESS) {
          return status;
      }
-@@ -342,6 +380,8 @@ enum nss_status _nss_mdns_gethostbyname3_r(
+@@ -297,6 +338,8 @@ enum nss_status _nss_mdns_gethostbyname3_r(
          return NSS_STATUS_TRYAGAIN;
      }

**Comment by mgorny** [comment]
Ping.

**Comment by agoode** [comment]
Sorry for the delay. I ended up copying your last giant comment into the commit message to document it. Thanks!

**Pull request merged**
